GET http://localhost:3000/kennzeichen/?id=6
###
GET http://localhost:3000/kennzeichen/
###
delete http://localhost:3000/kennzeichen/20
###
post http://127.0.0.1:3000/kennzeichen
Content-Type: application/json

{
    "bezirk": "OW",
    "nummer": "12 Ab"
}
