GET http://localhost:3000/kfz
###
GET http://localhost:3000/kennzeichen/
###
post http://127.0.0.1:3000/kfz
Content-Type: application/json

{
    "bezirk": "WU",
    "nummer": "1234 AB"
}
###
post http://127.0.0.1:3000/kennzeichen
Content-Type: application/json

{
    "name": "James Garner2",
    "image": "A",
    "born": "1999-12-12"
}
